### ISSUE TITLE
Support of .app splitting for cia-helper.py

### ISSUE THREAD

**Issue by Komfudo** [LetsShop3DS/shopdeck#1]
Originally Nintendo splitted the .app files.
i tested cia-helper.py and on super smash bros it made a massive .app file instead of splitting them.
Not sure how many Megabytes .app files are when downloading something on the 3ds Eshop.

Would be kinda interesting when implementing it...

**Comment by Rix565** [comment]
Your massive .app file is actually SSB main app file.
There are others .app files, but they are DLCs or Manuals.

**Comment by Komfudo** [comment]
So it's not like the wii u does?

**Comment by Rix565** [comment]
Nope. The Wii U _does_ split .app in multiple files, but not the 3DS.

**Comment by Komfudo** [comment]
understandable, time to close it

**Comment by Rix565** [comment]
This _could_ be a feature for 1.0, reopened.

**Comment by Rix565** [comment]
Fixed in 624c634.
