### ISSUE TITLE
[IDEA] Hshop & universal update repo integration 

### ISSUE THREAD

**Issue by EinfachEli08** [LetsShop3DS/shopdeck#11]
This would be so crazy if it had hshop, themeplaza (themes badges bootscreens etc) and even universal repo support!

THIS IS JUST AN IDEA.

**Comment by EinfachEli08** [comment]
I could write one!

**Comment by Rix565** [comment]
would not be possible, first i dont support piracy (hshop is automatically excluded), and the way universal updater works isnt how the eshop works, themeplaza **could** be possible tho.

**Comment by EinfachEli08** [comment]
As i Said, i could write something for that! But why not HShop? You could be giving the eshop its original flair back, wich is definetly possible

**Comment by EinfachEli08** [comment]
But what about themes tho

**Comment by Weigurde** [comment]
plus hshop's 3ds client is foss, you could just fork it and go make it look like the eshop yourself and then submit a pull request

**Comment by RengeLK** [comment]
3hs supports creating custom themes for itself, you can make it look like the e shop too if you wanted to
  
  
  
  
  
  
  

  
  
>

**Comment by Rix565** [comment]
Oh my god... I HAD ENOUGH. bye

**Comment by Rix565** [comment]
can you guys not read "we do not support piracy"????
